### ISSUE TITLE
Sigil groups

### ISSUE THREAD

**Issue by MrDragonorg** [ritzbits/sunrust-zs-fgd#1]
Add a new option for **info_sigilnode**, which will allow you to combine them into groups. 

This means that if a sigil randomly spawn at one of the points in this group, then the other sigil doesn't spawn at this point. This will be useful for many maps with sigils, so that the sigils can not spawn very close to each other, or so that they don't spawn in any specific places.

As an example, I can give a map _zs_vector_v2_, on which sigils can often spawn in small buildings, which greatly affects the gameplay, since many of these small buildings are more difficult to guard.

The function can be done in the form of a drop-down menu with a list of "Group 1, Group 2, etc."
_or_
As your own name assignment in the special box "Sigil Group"

**Comment by MagicSwap** [comment]
Seems straightforward enough, I'm unsure of whether sigils should be picked _within_ groups (i.e only spawn sigils within a randomly picked group) or exclude groups like you said (only pick sigils from 1 group each). Perhaps both behaviors could be implemented map-wide via gamerules or something. I'll look into it and see what seems more intuitive/easy to work with.
